name = "GNOM"
authors = ["Benoit Pasquier <briochemc@gmail.com>"]
version = "2.0.0"

[deps]
AIBECS = "ace601d6-714c-11e9-04e5-89b7fad23838"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemeTools = "d3e213a1-5e82-5c18-bb32-2a58a99f8c46"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
F1Method = "d5605bae-6d76-11e9-2fd7-71bcf42edbaa"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
GEOTRACES = "0fd43d8d-f157-424e-aaf7-32776c24e0de"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoRegions = "b001f823-fa75-4bff-bf55-6610c8f3688a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Inpaintings = "a3d749fb-087c-5225-80b3-65fbd02ae0fd"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
OceanBasins = "d1bb7020-b2be-4340-9d18-d24ca645bddb"
OceanGrids = "cfe838f4-859f-11e9-2ea1-df7d4e7c3537"
OceanographyCruises = "32ce50af-5875-4c4d-b676-f166988c519c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulMoles = "999f2bd7-36bf-5ba7-9bc1-c9473aa75374"
WorldOceanAtlasTools = "04f20302-f1b9-11e8-29d9-7d841cb0a64a"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
